
services:
  mysql:
    image: mysql:latest
    container_name: weather_data_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather_data_db  
      # MYSQL_USER: root                 
      # MYSQL_PASSWORD: root             
    volumes:
      - mysql-data:/var/lib/mysql      
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
